/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    '../../packages/ui/src/**/*.{js,ts,jsx,tsx}',
  ],
  safelist: [
    'bg-gradient-to-r',
    'from-blue-600',
    'to-blue-700',
    'from-blue-700',
    'to-blue-800',
    'from-gray-100',
    'to-gray-200',
    'from-gray-200',
    'to-gray-300',
    'from-red-600',
    'to-red-700',
    'from-red-700',
    'to-red-800',
    'from-green-600',
    'to-green-700',
    'from-green-700',
    'to-green-800',
    'from-yellow-500',
    'to-yellow-600',
    'from-yellow-600',
    'to-yellow-700',
    'hover:from-blue-700',
    'hover:to-blue-800',
    'hover:from-gray-200',
    'hover:to-gray-300',
    'hover:from-red-700',
    'hover:to-red-800',
    'hover:from-green-700',
    'hover:to-green-800',
    'hover:from-yellow-600',
    'hover:to-yellow-700',
    'shadow-lg',
    'hover:shadow-xl',
    'active:scale-95',
    'transform',
    'transition-all',
    'duration-200',
    'border-2',
    'rounded-full',
    'rounded-lg',
    'h-7',
    'h-8',
    'h-9',
    'h-10',
    'h-11',
    'h-12',
    'px-2',
    'px-3',
    'px-4',
    'px-6',
    'px-8',
    'py-2',
    'text-xs',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'w-full',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
        },
      },
    },
  },
  plugins: [],
}
